"""Stable contracts shared by the TestOps control plane and runners."""

from .capabilities import (
    ASSERTIONS,
    OPERATIONS,
    capability_payload,
    get_assertion_spec,
    get_operation_spec,
)
from .json_tools import canonical_json_bytes, canonical_sha256
from .models import (
    Artifact,
    ArtifactKind,
    AssertionDefinition,
    AutomationPackageRef,
    CaseBaseline,
    CaseBaselineRef,
    CaseBaselineSource,
    CaseDefinition,
    CasePriority,
    CaseResult,
    CaseResultStatus,
    CaseSourceTrace,
    DerivedCaseBaselineSource,
    RunResult,
    RunSnapshot,
    RunStatus,
    RuntimeVariable,
    SecretBinding,
    StepDefinition,
    TargetType,
    WebRunConfig,
)

__all__ = [
    "ASSERTIONS",
    "OPERATIONS",
    "Artifact",
    "ArtifactKind",
    "AssertionDefinition",
    "AutomationPackageRef",
    "CaseBaseline",
    "CaseBaselineRef",
    "CaseBaselineSource",
    "CaseDefinition",
    "CasePriority",
    "CaseResult",
    "CaseResultStatus",
    "CaseSourceTrace",
    "DerivedCaseBaselineSource",
    "RunResult",
    "RunSnapshot",
    "RunStatus",
    "RuntimeVariable",
    "SecretBinding",
    "StepDefinition",
    "TargetType",
    "WebRunConfig",
    "capability_payload",
    "canonical_json_bytes",
    "canonical_sha256",
    "get_assertion_spec",
    "get_operation_spec",
]
