"""Stable contracts shared by the TestOps control plane and runners."""

from .capabilities import (
    ASSERTIONS,
    OPERATIONS,
    capability_payload,
    get_assertion_spec,
    get_operation_spec,
)
from .json_tools import canonical_json_bytes, canonical_sha256
from .models import (
    Artifact,
    ArtifactKind,
    AssertionDefinition,
    AutomationPackageRef,
    AutomationPackageRuntimeRef,
    AutomationPackageSupplyChainRef,
    CaseBaseline,
    CaseBaselineRef,
    CaseBaselineSource,
    CaseDefinition,
    CasePriority,
    CaseResult,
    CaseResultStatus,
    CaseSourceTrace,
    DerivedCaseBaselineSource,
    RunExecutionIsolationEvidence,
    RunResult,
    RunSnapshot,
    RunStatus,
    RuntimeVariable,
    SecretBinding,
    StepDefinition,
    TargetType,
    WebRunConfig,
)
from .supply_chain_envelope import (
    ASYMMETRIC_ENVELOPE_PROFILE,
    JWS_TYPE,
    LEGACY_ENVELOPE_PROFILE,
    base64url_encode,
    supply_chain_asymmetric_envelope_payload,
    supply_chain_detached_jws_signing_input,
    supply_chain_envelope_signature_base,
    supply_chain_jws_protected_header,
)

__all__ = [
    "ASSERTIONS",
    "ASYMMETRIC_ENVELOPE_PROFILE",
    "JWS_TYPE",
    "LEGACY_ENVELOPE_PROFILE",
    "OPERATIONS",
    "Artifact",
    "ArtifactKind",
    "AssertionDefinition",
    "AutomationPackageRef",
    "AutomationPackageRuntimeRef",
    "AutomationPackageSupplyChainRef",
    "CaseBaseline",
    "CaseBaselineRef",
    "CaseBaselineSource",
    "CaseDefinition",
    "CasePriority",
    "CaseResult",
    "CaseResultStatus",
    "CaseSourceTrace",
    "DerivedCaseBaselineSource",
    "RunExecutionIsolationEvidence",
    "RunResult",
    "RunSnapshot",
    "RunStatus",
    "RuntimeVariable",
    "SecretBinding",
    "StepDefinition",
    "TargetType",
    "WebRunConfig",
    "base64url_encode",
    "capability_payload",
    "canonical_json_bytes",
    "canonical_sha256",
    "get_assertion_spec",
    "get_operation_spec",
    "supply_chain_asymmetric_envelope_payload",
    "supply_chain_detached_jws_signing_input",
    "supply_chain_envelope_signature_base",
    "supply_chain_jws_protected_header",
]
